### ISSUE TITLE
No Secure Cookie?

### ISSUE THREAD

**Issue by jamesgoodhouse** [rbcervilla/redisstore#1]
I did some digging and comparison of this session store vs another [redis store](https://github.com/boj/redistore/) as well as Gorilla's default cookie store, and I see that they are making use of [securecookie](https://github.com/gorilla/securecookie) to add a layer of security to the cookie. I am curious as to why this is not used in this store?

- https://github.com/boj/redistore/blob/cd5dcc76aeff9ba06b0a924829fe24fd69cdd517/redistore.go#L263
- https://github.com/gorilla/sessions/blob/master/store.go#L104

**Comment by rbcervilla** [comment]
Secure cookie is only needed on cookie store, because the session value is saved on the cookie (therefore is saved on the web browser). Redis store persits the session value on Redis, so the cookie only keeps the session ID (crypto random generated key).

The [boj redistore](https://github.com/boj/redistore/) implementation and others copied file store implementation (that used securecookie by mistake). You can see [issue](https://github.com/gorilla/sessions/issues/200) talking about this.

Also you can see how the GoogleCloud [Firestore](https://github.com/GoogleCloudPlatform/firestore-gorilla-sessions) implementation doesn't use secure cookie.

**Comment by idc77** [comment]
It's better to have a layer of protection vs no layer of protection.
I would not feel safe exposing the session id in clear text.
All you need is the session id, obtained by whatever means, and you have access to the complete session aka you can act as if you're the authenticated user without ever needing the whole security deal around autnz,
